apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example-app
  namespace: default
  labels:
    app: mux
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mux
  template:
    metadata:
      labels:
        app: mux
    spec:
      containers:
      - name: go-example-app
        image: joinnisacr.azurecr.io/go-example-app:latest
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "akvprovider-demo"
            nodePublishSecretRef:                       
              name: secrets-store-creds