# This is a SecretProviderClass example using service principal to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvprovider-demo
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: goexamplekeyvault
    objects:  |
      array:
        - |
          objectName: DemoSecret
          objectType: secret             
          objectVersion: ""              
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47                