apiVersion: v1
kind: Service
metadata:
  name: go-example-app-service
  namespace: default
  labels:
    app: go-example-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: go-example-app